### ISSUE TITLE
Failed to register/update a ServiceWorker for scope ‘https://auth.fission.codes/’

### ISSUE THREAD

**Issue by tennox** [jessmartin/fumblr#9]
When I try to authenticate via fission, I get a spinning yellow icon in the button and this error in console:
> Failed to register/update a ServiceWorker for scope ‘https://auth.fission.codes/’: Storage access is restricted in this context due to user settings or private browsing mode. [exchange.html:32:32](https://auth.fission.codes/exchange.html)

> Uncaught (in promise) DOMException: The operation is insecure. [exchange.html:32](https://auth.fission.codes/exchange.html)

> Partitioned cookie or storage access was provided to “https://auth.fission.codes/exchange.html” because it is loaded in the third-party context and dynamic state partitioning is enabled.

In: Firefox 103.0b2 (64-bit) on Fedora 36

Works in: Brave 1.40.107 Chromium: 103.0.5060.53 (Official Build) (64-bit)

I did not manage to try in a Firefox instance without my extensions, as the fission authentication failed with some error I think is not mumblr related

**Comment by jessmartin** [comment]
Thanks for reporting. I've run into some issues with Safari on macOS 11 as well. I'll look into it, but the place to get help would be the [Fission Discord](https://fission.codes/discord) in the #support channel.

**Comment by jessmartin** [comment]
Confirmed that it's not working in Firefox 102.01 on macOS 10.15.7.

![image](https://user-images.githubusercontent.com/27258/178570684-7af031a9-705e-404e-87cd-ddc1330c2923.png)

**Comment by jessmartin** [comment]
@tennox I figured out a (horrible) workaround. You have to disable "[Dynamic State Partitioning](https://developer.mozilla.org/en-US/docs/Web/Privacy/State_Partitioning#disable_dynamic_state_partitioning)" by setting an obscure setting in the special about:config settings in Firefox.

1. Open a new tab in Firefox and type `about:config`.
2. In the search box, type `network.cookie.cookieBehavior`.
3. Edit the value of that setting and set it to `0` (allow all).
4. Save the setting.
5. Open a new tab and go to https://mumblr.app (reloading an existing tab will still fail).

Here's what it will look like:
![image](https://user-images.githubusercontent.com/27258/178575341-a0a4bca7-c640-4343-877c-c636089085bd.png)

**Comment by tennox** [comment]
Oh, it's about strict mode...
Well, Firefox did warn that sites might break.
Fair enough.

Thanks for investigation and even inspiring the upstream fix/handling 👌

Closing this as I guess it's either upstream or wontfix... (Feel free to reopen at your discretion)

**Comment by jessmartin** [comment]
Leaving this closed, but I did discover a _much_ simpler fix: disable "Enhanced Tracking Protection."

Click the shield next to the URL and toggle it off like so:
![image](https://user-images.githubusercontent.com/27258/179523312-60734b34-5131-4f3e-8ab3-da498ff94c64.png)

**Comment by jeffgca** [comment]
@tennox thanks for filing this - fixes for these issues that we are discussing internally involve one or more directions:

1. ( near term ) we are working on de-coupling apps and authentication from the fission.codes auth system and fission.codes site, and as part of this we have discussed moving away from using shared workers. The root cause of these issues is some browsers not supporting shared workers and other resources across different domains as these techniques could be used to track users, and this area of browser features is not standardized.
2. ( later ) moving away from using js-ipfs / libp2p entirely in the browser. We currently use this technique because it is the current supported way to add data to ipfs, but as you can see browser support is problematic. There are other challenges to reliability and performance associated with this, especially on mobile. We are actively proposing new ways to enable adding data from apps to ipfs using standard http calls, and we hope to move quickly to implement these going forward.
